// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/ChartComponent/Chart.vue')['default']
    ChartHeader: typeof import('./src/components/ChartComponent/ChartHeader.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    Main: typeof import('./src/components/common/Main.vue')['default']
    Sidebar: typeof import('./src/components/common/Sidebar.vue')['default']
    SubMenu: typeof import('./src/components/common/SubMenu.vue')['default']
    Table: typeof import('./src/components/TableComponent/Table.vue')['default']
  }
}

export { }
