// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    Chart: typeof import('./components/charts/Chart.vue')['default']
    ChartHeader: typeof import('./components/charts/ChartHeader.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./components/common/Header.vue')['default']
    Layout: typeof import('./components/Layout/Layout.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    Main: typeof import('./components/common/Main.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    Sidebar: typeof import('./components/common/Sidebar.vue')['default']
    SubMenu: typeof import('./components/common/SubMenu.vue')['default']
    Table: typeof import('./components/TableComponent/Table.vue')['default']
    TableTree: typeof import('./components/TableComponent/TableTree.vue')['default']
    Tree: typeof import('./components/TreeComponent/Tree.vue')['default']
  }
}

export { }
